### ISSUE TITLE
Python 3.8 error

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#56]
I just got this error message when running nbpages on my cbe60499-instructor repository:

```
Traceback (most recent call last):
  File "/anaconda3/envs/spring2021/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 512, in convert_notebooks
    raise ValueError(
ValueError: Please specify an output format with '--to <format>'.
The following formats are available: ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf']
- writing python index
Traceback (most recent call last):
  File "/anaconda3/envs/spring2021/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/anaconda3/envs/spring2021/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 512, in convert_notebooks
    raise ValueError(
ValueError: Please specify an output format with '--to <format>'.
The following formats are available: ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides', 'webpdf']
```

Not sure if this is specific for Python 3.8 (my first guess).

**Comment by jckantor** [comment]
Yes, I had that, too, a few weeks ago. I did some bug fixes.  Are you using the latest and greatest?

Jeff

**Comment by adowling2** [comment]
Updating to the newest version fixed it!
